version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
      - FAISS_INDEX_PATH=/faiss_indices
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - faiss_indices:/faiss_indices

  frontend:
    build: ./frontend/idea-code-release-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network  # Добавлено подключение к сети

  rag-service:
    build: ./ai
    ports:
      - 3000:3000
    environment:
      - FAISS_INDEX_PATH=/faiss_indices
      - OLLAMA_API=http://ollama:11434
    volumes:
      - faiss_indices:/faiss_indices
    networks:
      - app-network

volumes:
  postgres_data:
  faiss_indices:

networks:
  app-network:
    driver: bridge